services:
  database:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: txgo-db
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - "./.docker/mysql:/var/lib/mysql"
