CREATE TABLE IF NOT EXISTS audit_actors(
    id VARCHAR(255) PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    audit_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,  

    FOREIGN KEY (audit_id) REFERENCES audits(id)
);