CREATE TABLE IF NOT EXISTS audits (
    id VARCHAR(255) PRIMARY KEY,
    module VARCHAR(255) NOT NULL,
    context VARCHAR(255) NOT NULL,
    message VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);