apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: txgo-dev
type: Opaque
stringData:
  MYSQL_USER: user
  MYSQL_PASSWORD: password
  MYSQL_DATABASE: db
  MYSQL_ROOT_PASSWORD: password
